*KEYWORD
*PART
Upper_Extremity_Soft_Tissue_Upper_Arm_Skin_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611110    611110    600110              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Upper_Arm_Skin_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611110         9     0.833        0.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
Upper_Extremity_Soft_Tissue_Upper_Arm_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    611112    611112    601110                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Upper_Arm_Left
$    SECID|   ELFORM|
    611112        -2
*PART
Upper_Extremity_Soft_Tissue_Upper_Arm_Muscle_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    611113    611113    601100                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Upper_Arm_Muscle_Left
$    SECID|   ELFORM|
    611113        -2
*PART_CONTACT
Upper Extremity_Soft_Tissue_Upper_Arm_Null_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611115    611115    709000                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper Extremity_Soft_Tissue_Upper_Arm_Null_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611115         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Elbow_Null
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611120    611120    611120                             0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Elbow_Null
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611120         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Elbow_Skin_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611121    611121    601120              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Elbow_Skin_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611121         9     0.833        0.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
Upper_Extremity_Soft_Tissue_Elbow_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    611122    611122    510020              100500         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Elbow_Left
$    SECID|   ELFORM|
    611122         1
*PART
Upper_Extremity_Soft_Tissue_Elbow_Muscle_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    611123    611123    510020              100500         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Elbow_Muscle_Left
$    SECID|   ELFORM|
    611123         1
*PART_CONTACT
Upper Extremity_Elbow_Soft_Tissue_Null_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611125    611125    709000                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper Extremity_Elbow_Soft_Tissue_Null_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611125         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART_CONTACT
Upper Extremity_Elbow_Soft_Tissue_Null_Edges_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611126    611126    709000                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper Extremity_Elbow_Soft_Tissue_Null_Edges_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611126         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Lower_Arm_Skin_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611131    611131    601120              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Lower_Arm_Skin_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611131         9     0.833        0.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
Upper_Extremity_Soft_Tissue_Lower_Arm
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    611132    611132    601100                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Lower_Arm
$    SECID|   ELFORM|
    611132        -2
*PART
Upper_Extremity_Soft_Tissue_Lower_Arm_Muscle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    611133    611133    601100                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Lower_Arm_Muscle
$    SECID|   ELFORM|
    611133        -2
*PART_CONTACT
Upper Extremity_Soft_Tissue_Null_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611135    611135    709000                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper Extremity_Soft_Tissue_Null_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611135         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Hand_Null
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611140    611140    611120                             0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Hand_Null
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611140         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Hand_Skin
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611141    611141    601140              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Hand_Skin
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611141         9        1.        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
Upper_Extremity_Soft_Tissue_Hand
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    611142    611142    601100                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Hand
$    SECID|   ELFORM|
    611142        -2
*PART
Upper_Extremity_Soft_Tissue_Skin_Contact_Transition_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    611151    611151    601120              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Skin_Contact_Transition_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    611151         9     0.833        0.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
Upper_Extremity_Bone_Clavicle_Cortical_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    612110    612110    602110                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Clavicle_Cortical_Left
$    SECID|   ELFORM|
    612110        -2
*PART
Upper_Extremity_Bone_Clavicle_Trabecular_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    612120    612120    602120                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Clavicle_Trabecular_Left
$    SECID|   ELFORM|
    612120        -2
*PART
Upper_Extremity_Bone_Scapula_Cortical
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    612210    612210    602210                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Scapula_Cortical
$    SECID|   ELFORM|
    612210        -2
*PART
Upper_Extremity_Bone_Scapula_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    612220    612220    602220                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Scapula_Trabecular
$    SECID|   ELFORM|
    612220        -2
*PART
Upper_Extremity_Bone_Humerus_Cortical
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    612310    612310    602310                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Humerus_Cortical
$    SECID|   ELFORM|
    612310        -2
*PART
Upper_Extremity_Bone_Humerus_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    612320    612320    602320                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Humerus_Trabecular
$    SECID|   ELFORM|
    612320        -2
*PART_CONTACT
Upper_Extremity_Bone_Ulna_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    612410    612410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Ulna_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    612410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Ulna_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    612420    612420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Ulna_Trabecular
$    SECID|   ELFORM|
    612420         1
*PART_CONTACT
Upper_Extremity_Bone_Radius_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    612510    612510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Radius_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    612510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Radius_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    612520    612520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Radius_Trabecular
$    SECID|   ELFORM|
    612520         1
*PART_CONTACT
Upper_Extremity_Bone_Scaphoid_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    613110    613110    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Scaphoid_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    613110         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Scaphoid_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    613120    613120    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Scaphoid_Trabecular
$    SECID|   ELFORM|
    613120         1
*PART_CONTACT
Upper_Extremity_Bone_Lunate_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    613210    613210    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Lunate_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    613210         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Lunate_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    613220    613220    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Lunate_Trabecular
$    SECID|   ELFORM|
    613220         1
*PART_CONTACT
Upper_Extremity_Bone_Triquetrum_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    613310    613310    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Triquetrum_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    613310         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Triquetrum_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    613320    613320    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Triquetrum_Trabecular
$    SECID|   ELFORM|
    613320         1
*PART_CONTACT
Upper_Extremity_Bone_Pisiform_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    613410    613410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Pisiform_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    613410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Pisiform_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    613420    613420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Pisiform_Trabecular
$    SECID|   ELFORM|
    613420         1
*PART_CONTACT
Upper_Extremity_Bone_Trapezium_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    613510    613510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Trapezium_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    613510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Trapezium_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    613520    613520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Trapezium_Trabecular
$    SECID|   ELFORM|
    613520         1
*PART_CONTACT
Upper_Extremity_Bone_Trapezoid_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    613610    613610    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Trapezoid_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    613610         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Trapezoid_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    613620    613620    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Trapezoid_Trabecular
$    SECID|   ELFORM|
    613620         1
*PART_CONTACT
Upper_Extremity_Bone_Capitate_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    613710    613710    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Capitate_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    613710         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Capitate_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    613720    613720    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Capitate_Trabecular
$    SECID|   ELFORM|
    613720         1
*PART_CONTACT
Upper_Extremity_Bone_Hamate_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    613810    613810    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Hamate_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    613810         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Hamate_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    613820    613820    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Hamate_Trabecular
$    SECID|   ELFORM|
    613820         1
*PART
Upper_Extremity_Ligament_Wrist_Metacarpal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    614050    614050    604050              100800         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Ligament_Wrist_Metacarpal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    614050        16        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    614110    614110    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    614110         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    614120    614120    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    614120         1
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    614210    614210    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    614210         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    614220    614220    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    614220         1
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    614310    614310    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    614310         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    614320    614320    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    614320         1
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    614410    614410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    614410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    614420    614420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    614420         1
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    614510    614510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    614510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    614520    614520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    614520         1
*PART
Upper_Extremity_Ligament_Metacarpal_Phalanx
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    614550    614550    604050              100800         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Ligament_Metacarpal_Phalanx
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    614550        16        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
*PART
Upper_Extremity_Ligament_Phalanx_Proximal_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615050    615050    604050              100800         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Ligament_Phalanx_Proximal_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615050        16        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615110    615110    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615110         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    615120    615120    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    615120         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615210    615210    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615210         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    615220    615220    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    615220         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615310    615310    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615310         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    615320    615320    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    615320         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615410    615410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    615420    615420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    615420         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615510    615510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    615520    615520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    615520         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615610    615610    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615610         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    615620    615620    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    615620         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615710    615710    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615710         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    615720    615720    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    615720         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615810    615810    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615810         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    615820    615820    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    615820         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    615910    615910    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    615910         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    615920    615920    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    615920         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    616010    616010    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    616010         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    616020    616020    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    616020         1
*PART
Upper_Extremity_Ligament_Phalanx_Middle_distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    616050    616050    604050              100800         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Ligament_Phalanx_Middle_distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    616050        16        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    616210    616210    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    616210         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    616220    616220    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$    SECID|   ELFORM|
    616220         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    616310    616310    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    616310         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    616320    616320    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$    SECID|   ELFORM|
    616320         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    616410    616410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    616410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    616420    616420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$    SECID|   ELFORM|
    616420         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    616510    616510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    616510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    616520    616520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$    SECID|   ELFORM|
    616520         1
*PART
Upper_Extremity_Ligament_PROXIMALPHALANX_TO_DISTALPHALANX
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617700    617700    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_PROXIMALPHALANX_TO_DISTALPHALANX
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617700         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_MIDDLEPHALANX_TO_DISTALPHALANX
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617710    617710    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_MIDDLEPHALANX_TO_DISTALPHALANX
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617710         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_MIDDLEPHALANX_TO_METACARPAL
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617720    617720    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_MIDDLEPHALANX_TO_METACARPAL
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617720         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_METACARPALBONES
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617730    617730    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_METACARPALBONES
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617730         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_WRIST_TO_METACARPAL
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617740    617740    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_WRIST_TO_METACARPAL
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617740         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_TRAPEZIOTRAPEZOID
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617750    617750    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_TRAPEZIOTRAPEZOID
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617750         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_CAPITOTRAPEZOID
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617760    617760    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_CAPITOTRAPEZOID
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617760         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_SCAPHOCAPITATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617770    617770    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_SCAPHOCAPITATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617770         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_SCAPHOLUNATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617780    617780    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_SCAPHOLUNATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617780         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_LUNOTRIQUETRAL
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617790    617790    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_LUNOTRIQUETRAL
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617790         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_CAPITOHAMATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617800    617800    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_CAPITOHAMATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617800         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_TRIQUETROHAMATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617810    617810    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_TRIQUETROHAMATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617810         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_TRIQUETROCAPITATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617820    617820    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_TRIQUETROCAPITATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617820         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_SCAPHOTRAPEZIUMTRAPEZOID
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617830    617830    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_SCAPHOTRAPEZIUMTRAPEZOID
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617830         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_PISIFORM_TO_WRISTBONES
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617840    617840    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_PISIFORM_TO_WRISTBONES
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617840         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_RADIUS_TO_WRIST
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617870    617870    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_RADIUS_TO_WRIST
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617870         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_ULNA_TO_WRIST
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617880    617880    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_ULNA_TO_WRIST
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617880         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_ULNA_TO_RADIUS
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    617890    617890    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_ULNA_TO_RADIUS
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    617890         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Soft_Tissue_Upper_Arm_Skin_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661110    661110    600110              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Upper_Arm_Skin_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661110         9     0.833        0.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.      -90.
*PART
Upper_Extremity_Soft_Tissue_Upper_Arm_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    661112    661112    601110                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Upper_Arm_Left
$    SECID|   ELFORM|
    661112        -2
*PART
Upper_Extremity_Soft_Tissue_Upper_Arm_Muscle_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    661113    661113    601100                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Upper_Arm_Muscle_Left
$    SECID|   ELFORM|
    661113        -2
*PART_CONTACT
Upper Extremity_Soft_Tissue_Upper_Arm_Null_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661115    661115    709000                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper Extremity_Soft_Tissue_Upper_Arm_Null_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661115         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Elbow_Null
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661120    661120    611120                             0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Elbow_Null
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661120         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Elbow_Skin_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661121    661121    601120              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Elbow_Skin_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661121         9     0.833        0.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.      -90.
*PART
Upper_Extremity_Soft_Tissue_Elbow_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    661122    661122    510020              100500         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Elbow_Left
$    SECID|   ELFORM|
    661122         1
*PART
Upper_Extremity_Soft_Tissue_Elbow_Muscle_Left
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    661123    661123    510020              100500         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Elbow_Muscle_Left
$    SECID|   ELFORM|
    661123         1
*PART_CONTACT
Upper Extremity_Elbow_Soft_Tissue_Null_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661125    661125    709000                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper Extremity_Elbow_Soft_Tissue_Null_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661125         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART_CONTACT
Upper Extremity_Elbow_Soft_Tissue_Null_Edges_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661126    661126    709000                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper Extremity_Elbow_Soft_Tissue_Null_Edges_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661126         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Lower_Arm_Skin_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661131    661131    601120              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Lower_Arm_Skin_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661131         9     0.833        0.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.      -90.
*PART
Upper_Extremity_Soft_Tissue_Lower_Arm
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    661132    661132    601100                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Lower_Arm
$    SECID|   ELFORM|
    661132        -2
*PART
Upper_Extremity_Soft_Tissue_Lower_Arm_Muscle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    661133    661133    601100                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Lower_Arm_Muscle
$    SECID|   ELFORM|
    661133        -2
*PART_CONTACT
Upper Extremity_Soft_Tissue_Null_Left
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661135    661135    709000                             0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper Extremity_Soft_Tissue_Null_Left
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661135         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Hand_Null
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661140    661140    611120                             0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Hand_Null
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661140         2        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Upper_Extremity_Soft_Tissue_Hand_Skin
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661141    661141    601140              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Hand_Skin
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661141         9        1.        1.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.      -90.
*PART
Upper_Extremity_Soft_Tissue_Hand
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    661142    661142    601100                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Soft_Tissue_Hand
$    SECID|   ELFORM|
    661142        -2
*PART
Upper_Extremity_Soft_Tissue_Skin_Contact_Transition_Right
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    661151    661151    601120              100300         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Soft_Tissue_Skin_Contact_Transition_Right
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    661151         9     0.833        0.        1.         0         1
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
$       B1|       B2|
        0.       90.
*PART
Upper_Extremity_Bone_Clavicle_Cortical_Right
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    662110    662110    602110                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Clavicle_Cortical_Right
$    SECID|   ELFORM|
    662110        -2
*PART
Upper_Extremity_Bone_Clavicle_Trabecular_right
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    662120    662120    602120                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Clavicle_Trabecular_right
$    SECID|   ELFORM|
    662120        -2
*PART
Upper_Extremity_Bone_Scapula_Cortical
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    662210    662210    602210                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Scapula_Cortical
$    SECID|   ELFORM|
    662210        -2
*PART
Upper_Extremity_Bone_Scapula_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    662220    662220    602220                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Scapula_Trabecular
$    SECID|   ELFORM|
    662220        -2
*PART
Upper_Extremity_Bone_Humerus_Cortical
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    662310    662310    602310                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Humerus_Cortical
$    SECID|   ELFORM|
    662310        -2
*PART
Upper_Extremity_Bone_Humerus_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    662320    662320    602320                             0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Humerus_Trabecular
$    SECID|   ELFORM|
    662320        -2
*PART_CONTACT
Upper_Extremity_Bone_Ulna_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    662410    662410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Ulna_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    662410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Ulna_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    662420    662420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Ulna_Trabecular
$    SECID|   ELFORM|
    662420         1
*PART_CONTACT
Upper_Extremity_Bone_Radius_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    662510    662510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Radius_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    662510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Radius_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    662520    662520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Radius_Trabecular
$    SECID|   ELFORM|
    662520         1
*PART_CONTACT
Upper_Extremity_Bone_Scaphoid_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    663110    663110    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Scaphoid_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    663110         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Scaphoid_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    663120    663120    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Scaphoid_Trabecular
$    SECID|   ELFORM|
    663120         1
*PART_CONTACT
Upper_Extremity_Bone_Lunate_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    663210    663210    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Lunate_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    663210         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Lunate_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    663220    663220    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Lunate_Trabecular
$    SECID|   ELFORM|
    663220         1
*PART_CONTACT
Upper_Extremity_Bone_Triquetrum_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    663310    663310    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Triquetrum_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    663310         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Triquetrum_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    663320    663320    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Triquetrum_Trabecular
$    SECID|   ELFORM|
    663320         1
*PART_CONTACT
Upper_Extremity_Bone_Pisiform_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    663410    663410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Pisiform_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    663410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Pisiform_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    663420    663420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Pisiform_Trabecular
$    SECID|   ELFORM|
    663420         1
*PART_CONTACT
Upper_Extremity_Bone_Trapezium_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    663510    663510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Trapezium_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    663510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Trapezium_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    663520    663520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Trapezium_Trabecular
$    SECID|   ELFORM|
    663520         1
*PART_CONTACT
Upper_Extremity_Bone_Trapezoid_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    663610    663610    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Trapezoid_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    663610         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Trapezoid_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    663620    663620    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Trapezoid_Trabecular
$    SECID|   ELFORM|
    663620         1
*PART_CONTACT
Upper_Extremity_Bone_Capitate_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    663710    663710    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Capitate_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    663710         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Capitate_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    663720    663720    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Capitate_Trabecular
$    SECID|   ELFORM|
    663720         1
*PART_CONTACT
Upper_Extremity_Bone_Hamate_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    663810    663810    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Hamate_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    663810         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Hamate_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    663820    663820    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Hamate_Trabecular
$    SECID|   ELFORM|
    663820         1
*PART
Upper_Extremity_Ligament_Wrist_Metacarpal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    664050    664050    604050              100800         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Ligament_Wrist_Metacarpal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    664050        16        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    664110    664110    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    664110         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    664120    664120    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    664120         1
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    664210    664210    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    664210         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    664220    664220    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    664220         1
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    664310    664310    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    664310         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    664320    664320    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    664320         1
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    664410    664410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    664410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    664420    664420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    664420         1
*PART_CONTACT
Upper_Extremity_Bone_Metacarpal_Cortical
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    664510    664510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Metacarpal_Cortical
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    664510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Metacarpal_Trabecular
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    664520    664520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Metacarpal_Trabecular
$    SECID|   ELFORM|
    664520         1
*PART
Upper_Extremity_Ligament_Metacarpal_Phalanx
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    664550    664550    604050              100800         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Ligament_Metacarpal_Phalanx
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    664550        16        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
*PART
Upper_Extremity_Ligament_Phalanx_Proximal_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665050    665050    604050              100800         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Ligament_Phalanx_Proximal_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665050        16        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665110    665110    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665110         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    665120    665120    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    665120         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665210    665210    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665210         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    665220    665220    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    665220         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665310    665310    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665310         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    665320    665320    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    665320         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665410    665410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    665420    665420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    665420         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665510    665510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Proximal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    665520    665520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Proximal
$    SECID|   ELFORM|
    665520         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665610    665610    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665610         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    665620    665620    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    665620         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665710    665710    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665710         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    665720    665720    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    665720         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665810    665810    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665810         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    665820    665820    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    665820         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    665910    665910    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    665910         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    665920    665920    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    665920         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    666010    666010    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Middle
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    666010         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    666020    666020    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Middle
$    SECID|   ELFORM|
    666020         1
*PART
Upper_Extremity_Ligament_Phalanx_Middle_distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    666050    666050    604050              100800         0         0          
*SECTION_SHELL_TITLE
Upper_Extremity_Ligament_Phalanx_Middle_distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    666050        16        1.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        3.        3.        3.        3.        0.                  0.          
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    666210    666210    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    666210         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    666220    666220    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$    SECID|   ELFORM|
    666220         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    666310    666310    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    666310         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    666320    666320    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$    SECID|   ELFORM|
    666320         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    666410    666410    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    666410         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    666420    666420    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$    SECID|   ELFORM|
    666420         1
*PART_CONTACT
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    666510    666510    602400              100300         0         0          
$       FS|       FD|       DC|       VC|     OPTT|      SFT|      SSF|
        0.        0.        0.        0.       0.6        0.        0.
*SECTION_SHELL_TITLE
Upper_Extremity_Bone_Phalanx_Cortical_Distal
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    666510         2        1.        2.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        2.        2.        2.        2.        0.                  0.          
*PART
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$      PID|    SECID|      MID|    EOSID|     HGID|     GRAV|   ADPOPT|     TMID|
    666520    666520    602420              100200         0         0          
*SECTION_SOLID_TITLE
Upper_Extremity_Bone_Phalanx_Trabecular_Distal
$    SECID|   ELFORM|
    666520         1
*PART
Upper_Extremity_Ligament_PROXIMALPHALANX_TO_DISTALPHALANX
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667700    667700    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_PROXIMALPHALANX_TO_DISTALPHALANX
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667700         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_MIDDLEPHALANX_TO_DISTALPHALANX
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667710    667710    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_MIDDLEPHALANX_TO_DISTALPHALANX
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667710         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_MIDDLEPHALANX_TO_METACARPAL
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667720    667720    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_MIDDLEPHALANX_TO_METACARPAL
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667720         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_METACARPALBONES
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667730    667730    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_METACARPALBONES
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667730         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_WRIST_TO_METACARPAL
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667740    667740    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_WRIST_TO_METACARPAL
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667740         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_TRAPEZIOTRAPEZOID
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667750    667750    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_TRAPEZIOTRAPEZOID
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667750         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_CAPITOTRAPEZOID
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667760    667760    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_CAPITOTRAPEZOID
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667760         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_SCAPHOCAPITATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667770    667770    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_SCAPHOCAPITATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667770         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_SCAPHOLUNATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667780    667780    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_SCAPHOLUNATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667780         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_LUNOTRIQUETRAL
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667790    667790    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_LUNOTRIQUETRAL
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667790         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_CAPITOHAMATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667800    667800    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_CAPITOHAMATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667800         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_TRIQUETROHAMATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667810    667810    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_TRIQUETROHAMATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667810         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_TRIQUETROCAPITATE
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667820    667820    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_TRIQUETROCAPITATE
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667820         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_SCAPHOTRAPEZIUMTRAPEZOID
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667830    667830    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_SCAPHOTRAPEZIUMTRAPEZOID
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667830         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_PISIFORM_TO_WRISTBONES
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667840    667840    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_PISIFORM_TO_WRISTBONES
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667840         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_RADIUS_TO_WRIST
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667870    667870    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_RADIUS_TO_WRIST
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667870         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_ULNA_TO_WRIST
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667880    667880    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_ULNA_TO_WRIST
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667880         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Upper_Extremity_Ligament_ULNA_TO_RADIUS
$      PID|    SECID|      MID|         |     HGID|     GRAV|         |     TMID|
    667890    667890    607700                             0                    
*SECTION_BEAM_TITLE
Upper_Extremity_Ligament_ULNA_TO_RADIUS
$    SECID|   ELFORM|     SHRF|  QR/IRID|      CST|    SCOOR|      NSM|
    667890         6                                      0.          
$      VOL|     INER|      CID|       CA|   OFFSET|    RRCON|    SRCON|    TRCON|
       10.     0.001                  0.        0.        0.        0.        0.
*PART
Thorax_Upper_Extremity_Null
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    710050    710050    700050                             0         0          
*SECTION_SHELL_TITLE
Thorax_Upper_Extremity_Null
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    710050         2        0.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*PART
Thorax_Upper_Extremity_Null
$      PID|    SECID|      MID|         |     HGID|     GRAV|   ADPOPT|     TMID|
    760050    760050    700050                             0         0          
*SECTION_SHELL_TITLE
Thorax_Upper_Extremity_Null
$    SECID|   ELFORM|     SHRF|      NIP|    PROPT|  QR/IRID|    ICOMP|
    760050         2        0.        1.        1.         0         0
$       T1|       T2|       T3|       T4|     NLOC|    MAREA|     IDOF|   EDGSET|
        1.        1.        1.        1.        0.                  0.          
*DEFINE_COORDINATE_NODES_TITLE
Left humerus upper
    612310   1004102   1004103   1004098         1Y         
*DEFINE_COORDINATE_NODES_TITLE
Left humerus lower
    612320   1003613   1003595   1003612         1Y         
*DEFINE_COORDINATE_NODES_TITLE
Left distal forearm
    612410   1016442   1016434   1016450         1Y         
$ANSA_COLOR;611110;SECTION_SHELL;.980392158031464;.494117647409439;.729411780834
$198;0.5;
$ANSA_COLOR;611112;SECTION_SOLID;0.5686274766922;.164705887436867;.9215686321258
$54;0.5;
$ANSA_COLOR;611113;SECTION_SOLID;0.65490198135376;.831372559070587;.109803922474
$384;0.5;
$ANSA_COLOR;611115;SECTION_SHELL;.933333337306976;.372549027204514;.905882358551
$025;1.;
$ANSA_COLOR;611120;SECTION_SHELL;0.95686274766922;.501960813999176;.670588254928
$589;0.5;
$ANSA_COLOR;611121;SECTION_SHELL;0.65490198135376;.815686285495758;.823529422283
$173;1.;
$ANSA_COLOR;611122;SECTION_SOLID;.968627452850342;.066666670143604;.556862771511
$078;0.5;
$ANSA_COLOR;611123;SECTION_SOLID;.627451002597809;.462745100259781;.588235318660
$736;0.5;
$ANSA_COLOR;611125;SECTION_SHELL;.623529434204102;0.7843137383461;.4549019634723
$66;1.;
$ANSA_COLOR;611126;SECTION_SHELL;.839215695858002;.831372559070587;.411764711141
$586;1.;
$ANSA_COLOR;611131;SECTION_SHELL;.905882358551025;.772549033164978;.200000002980
$232;1.;
$ANSA_COLOR;611132;SECTION_SOLID;.807843148708344;.992156863212585;.388235300779
$343;0.5;
$ANSA_COLOR;611133;SECTION_SOLID;.831372559070587;.121568627655506;.156862750649
$452;0.5;
$ANSA_COLOR;611135;SECTION_SHELL;0.95686274766922;.396078437566757;.572549045085
$907;0.5;
$ANSA_COLOR;611140;SECTION_SHELL;.756862759590149;.760784327983856;.725490212440
$491;0.5;
$ANSA_COLOR;611141;SECTION_SHELL;.843137264251709;.431372553110123;0.91372549533
$844;1.;
$ANSA_COLOR;611142;SECTION_SOLID;.670588254928589;.090196080505848;.533333361148
$834;1.;
$ANSA_COLOR;611151;SECTION_SHELL;.639215707778931;.890196084976196;.674509823322
$296;1.;
$ANSA_COLOR;612110;SECTION_SOLID;.694117665290833;.129411771893501;.541176497936
$249;0.5;
$ANSA_COLOR;612120;SECTION_SOLID;.607843160629272;.458823531866074;.352941185235
$977;0.5;
$ANSA_COLOR;612210;SECTION_SOLID;.682352960109711;.925490200519562;.149019613862
$038;0.5;
$ANSA_COLOR;612220;SECTION_SOLID;.596078455448151;.258823543787003;0.95686274766
$922;0.5;
$ANSA_COLOR;612310;SECTION_SOLID;.823529422283173;0.87058824300766;.321568638086
$319;0.5;
$ANSA_COLOR;612320;SECTION_SOLID;.737254917621613;.200000002980232;.129411771893
$501;0.5;
$ANSA_COLOR;612410;SECTION_SHELL;.996078431606293;.752941191196442;.152941182255
$745;0.5;
$ANSA_COLOR;612420;SECTION_SOLID;.584313750267029;.419607847929001;.345098048448
$563;0.5;
$ANSA_COLOR;612510;SECTION_SHELL;.952941179275513;.329411774873734;.223529413342
$476;0.5;
$ANSA_COLOR;612520;SECTION_SOLID;.537254929542542;0.;.411764711141586;0.5;
$ANSA_COLOR;613110;SECTION_SHELL;.898039221763611;.878431379795074;0.56862747669
$22;0.5;
$ANSA_COLOR;613120;SECTION_SOLID;.984313726425171;.549019634723663;.760784327983
$856;0.5;
$ANSA_COLOR;613210;SECTION_SHELL;.549019634723663;.200000002980232;.807843148708
$344;0.5;
$ANSA_COLOR;613220;SECTION_SOLID;.635294139385223;0.87058824300766;0.;0.5;
$ANSA_COLOR;613310;SECTION_SHELL;.921568632125854;.898039221763611;.709803938865
$662;0.5;
$ANSA_COLOR;613320;SECTION_SOLID;.509803950786591;0.5686274766922;.8980392217636
$11;0.5;
$ANSA_COLOR;613410;SECTION_SHELL;.721568644046783;.541176497936249;0.18823529779
$911;0.5;
$ANSA_COLOR;613420;SECTION_SOLID;.811764717102051;.207843139767647;.380392163991
$928;0.5;
$ANSA_COLOR;613510;SECTION_SHELL;.572549045085907;.219607844948769;.949019610881
$805;0.5;
$ANSA_COLOR;613520;SECTION_SOLID;.658823549747467;.890196084976196;.141176477074
$623;0.5;
$ANSA_COLOR;613610;SECTION_SHELL;.745098054409027;.560784339904785;.329411774873
$734;0.5;
$ANSA_COLOR;613620;SECTION_SOLID;.835294127464294;0.23137255012989;.521568655967
$712;0.5;
$ANSA_COLOR;613710;SECTION_SHELL;.933333337306976;0.10196078568697;.105882354080
$677;0.5;
$ANSA_COLOR;613720;SECTION_SOLID;.517647087574005;.772549033164978;.294117659330
$368;0.5;
$ANSA_COLOR;613810;SECTION_SHELL;.968627452850342;.937254905700684;.992156863212
$585;0.5;
$ANSA_COLOR;613820;SECTION_SOLID;.556862771511078;.607843160629272;.180392161011
$696;0.5;
$ANSA_COLOR;614050;SECTION_SHELL;.650980412960052;.686274528503418;.745098054409
$027;0.5;
$ANSA_COLOR;614110;SECTION_SHELL;.678431391716003;.501960813999176;.905882358551
$025;0.5;
$ANSA_COLOR;614120;SECTION_SOLID;.764705896377563;.168627455830574;.098039217293
$262;0.5;
$ANSA_COLOR;614210;SECTION_SHELL;.980392158031464;.141176477074623;.388235300779
$343;0.5;
$ANSA_COLOR;614220;SECTION_SOLID;.564705908298492;.811764717102051;.576470613479
$614;0.5;
$ANSA_COLOR;614310;SECTION_SHELL;0.65490198135376;.482352942228317;.764705896377
$563;0.5;
$ANSA_COLOR;614320;SECTION_SOLID;0.74117648601532;.149019613862038;0.95686274766
$922;0.5;
$ANSA_COLOR;614410;SECTION_SHELL;.501960813999176;.160784319043159;0.52549022436
$142;0.5;
$ANSA_COLOR;614420;SECTION_SOLID;.588235318660736;.831372559070587;.717647075653
$076;0.5;
$ANSA_COLOR;614510;SECTION_SHELL;0.82745099067688;.819607853889465;0.14509804546
$833;0.5;
$ANSA_COLOR;614520;SECTION_SOLID;0.91372549533844;.490196079015732;.337254911661
$148;0.5;
$ANSA_COLOR;614550;SECTION_SHELL;.560784339904785;.019607843831182;.552941203117
$371;0.5;
$ANSA_COLOR;615050;SECTION_SHELL;.976470589637756;0.34901961684227;.364705890417
$099;0.5;
$ANSA_COLOR;615110;SECTION_SHELL;.792156875133514;.600000023841858;0.61176472902
$298;0.5;
$ANSA_COLOR;615120;SECTION_SOLID;.882352948188782;.270588248968124;.800000011920
$929;0.5;
$ANSA_COLOR;615210;SECTION_SHELL;.596078455448151;.239215686917305;.090196080505
$848;0.5;
$ANSA_COLOR;615220;SECTION_SOLID;.682352960109711;.909803926944733;.278431385755
$539;0.5;
$ANSA_COLOR;615310;SECTION_SHELL;.768627464771271;.580392181873322;.470588237047
$195;0.5;
$ANSA_COLOR;615320;SECTION_SOLID;.858823537826538;.250980406999588;.658823549747
$467;0.5;
$ANSA_COLOR;615410;SECTION_SHELL;.619607865810394;.258823543787003;0.23137255012
$989;0.5;
$ANSA_COLOR;615420;SECTION_SOLID;.705882370471954;.929411768913269;.419607847929
$001;0.5;
$ANSA_COLOR;615510;SECTION_SHELL;.945098042488098;.917647063732147;.850980401039
$124;0.5;
$ANSA_COLOR;615520;SECTION_SOLID;.533333361148834;.588235318660736;.039215687662
$363;0.5;
$ANSA_COLOR;615610;SECTION_SHELL;.803921580314636;.800000011920929;.007843137718
$737;0.5;
$ANSA_COLOR;615620;SECTION_SOLID;.890196084976196;.470588237047195;.196078434586
$525;0.5;
$ANSA_COLOR;615710;SECTION_SHELL;.850980401039124;.839215695858002;.286274522542
$953;0.5;
$ANSA_COLOR;615720;SECTION_SOLID;.937254905700684;.509803950786591;0.47843137383
$461;0.5;
$ANSA_COLOR;615810;SECTION_SHELL;0.52549022436142;.180392161011696;.666666686534
$882;0.5;
$ANSA_COLOR;615820;SECTION_SOLID;0.61176472902298;.850980401039124;.858823537826
$538;0.5;
$ANSA_COLOR;615910;SECTION_SHELL;.874509811401367;.858823537826538;.427450984716
$415;0.5;
$ANSA_COLOR;615920;SECTION_SOLID;.960784316062927;.529411792755127;.619607865810
$394;0.5;
$ANSA_COLOR;616010;SECTION_SHELL;0.69803923368454;.521568655967712;.047058824449
$778;0.5;
$ANSA_COLOR;616020;SECTION_SOLID;.788235306739807;0.18823529779911;.239215686917
$305;0.5;
$ANSA_COLOR;616050;SECTION_SHELL;.886274516582489;.678431391716003;.172549024224
$281;0.5;
$ANSA_COLOR;616210;SECTION_SHELL;.607843160629272;.439215689897537;.486274510622
$025;0.5;
$ANSA_COLOR;616220;SECTION_SOLID;.694117665290833;.109803922474384;.674509823322
$296;0.5;
$ANSA_COLOR;616310;SECTION_SHELL;.780392169952393;.780392169952393;.866666674613
$953;0.5;
$ANSA_COLOR;616320;SECTION_SOLID;.866666674613953;.450980395078659;.054901961237
$192;0.5;
$ANSA_COLOR;616410;SECTION_SHELL;.631372570991516;.458823531866074;.627451002597
$809;0.5;
$ANSA_COLOR;616420;SECTION_SOLID;.541176497936249;.792156875133514;0.43529412150
$383;0.5;
$ANSA_COLOR;616510;SECTION_SHELL;0.95686274766922;.121568627655506;0.24705882370
$472;0.5;
$ANSA_COLOR;616520;SECTION_SOLID;.717647075653076;.129411771893501;.815686285495
$758;0.5;
$ANSA_COLOR;617700;SECTION_BEAM_ELFORM_6;.643137276172638;.278431385755539;.3725
$49027204514;1.;
$ANSA_COLOR;617710;SECTION_BEAM_ELFORM_6;.729411780834198;.949019610881805;.5607
$84339904785;1.;
$ANSA_COLOR;617720;SECTION_BEAM_ELFORM_6;.815686285495758;.619607865810394;.7529
$41191196442;1.;
$ANSA_COLOR;617730;SECTION_BEAM_ELFORM_6;.905882358551025;.290196090936661;.9411
$76474094391;1.;
$ANSA_COLOR;617740;SECTION_BEAM_ELFORM_6;.992156863212585;0.95686274766922;.1333
$33340287209;1.;
$ANSA_COLOR;617750;SECTION_BEAM_ELFORM_6;.580392181873322;.627451002597809;.3215
$68638086319;1.;
$ANSA_COLOR;617760;SECTION_BEAM_ELFORM_6;.666666686534882;.298039227724075;.5137
$25519180298;1.;
$ANSA_COLOR;617770;SECTION_BEAM_ELFORM_6;.752941191196442;.968627452850342;.7019
$60802078247;1.;
$ANSA_COLOR;617780;SECTION_BEAM_ELFORM_6;.839215695858002;.639215707778931;.8941
$17653369904;1.;
$ANSA_COLOR;617790;SECTION_BEAM_ELFORM_6;.929411768913269;.309803932905197;.0823
$52943718433;1.;
$ANSA_COLOR;617800;SECTION_BEAM_ELFORM_6;.513725519180298;.980392158031464;.2745
$09817361832;1.;
$ANSA_COLOR;617810;SECTION_BEAM_ELFORM_6;.603921592235565;.647058844566345;.4627
$45100259781;1.;
$ANSA_COLOR;617820;SECTION_BEAM_ELFORM_6;.690196096897125;.317647069692612;0.654
$90198135376;1.;
$ANSA_COLOR;617830;SECTION_BEAM_ELFORM_6;.776470601558685;.988235294818878;.8431
$37264251709;1.;
$ANSA_COLOR;617840;SECTION_BEAM_ELFORM_6;.862745106220245;.658823549747467;.0313
$72550874949;1.;
$ANSA_COLOR;617870;SECTION_BEAM_ELFORM_6;.627451002597809;.666666686534882;.6039
$21592235565;1.;
$ANSA_COLOR;617880;SECTION_BEAM_ELFORM_6;.713725507259369;.337254911661148;.7921
$56875133514;1.;
$ANSA_COLOR;617890;SECTION_BEAM_ELFORM_6;.800000011920929;.007843137718737;.9843
$13726425171;1.;
$ANSA_COLOR;661110;SECTION_SHELL;.815686285495758;.160784319043159;.309803932905
$197;1.;
$ANSA_COLOR;661112;SECTION_SOLID;.517647087574005;.450980395078659;.035294119268
$656;1.;
$ANSA_COLOR;661113;SECTION_SOLID;.721568644046783;0.;.505882382392883;1.;
$ANSA_COLOR;661115;SECTION_SHELL;.737254917621613;.878431379795074;.682352960109
$711;1.;
$ANSA_COLOR;661120;SECTION_SHELL;.807843148708344;.215686276555061;.431372553110
$123;1.;
$ANSA_COLOR;661121;SECTION_SHELL;.835294127464294;.976470589637756;0.78431373834
$61;1.;
$ANSA_COLOR;661122;SECTION_SOLID;0.91372549533844;0.30588236451149;.960784316062
$927;1.;
$ANSA_COLOR;661123;SECTION_SOLID;.596078455448151;.094117648899555;.501960813999
$176;1.;
$ANSA_COLOR;661125;SECTION_SHELL;.960784316062927;.937254905700684;.909803926944
$733;1.;
$ANSA_COLOR;661126;SECTION_SHELL;.752941191196442;.333333343267441;.890196084976
$196;1.;
$ANSA_COLOR;661131;SECTION_SHELL;.709803938865662;.858823537826538;.588235318660
$736;1.;
$ANSA_COLOR;661132;SECTION_SOLID;0.91372549533844;.254901975393295;.411764711141
$586;1.;
$ANSA_COLOR;661133;SECTION_SOLID;.517647087574005;.658823549747467;0.23137255012
$989;1.;
$ANSA_COLOR;661135;SECTION_SHELL;.952941179275513;.788235306739807;.839215695858
$002;1.;
$ANSA_COLOR;661140;SECTION_SHELL;.843137264251709;.023529412224889;.756862759590
$149;1.;
$ANSA_COLOR;661141;SECTION_SHELL;.658823549747467;.129411771893501;.117647059261
$799;1.;
$ANSA_COLOR;661142;SECTION_SOLID;.717647075653076;.796078443527222;.886274516582
$489;1.;
$ANSA_COLOR;661151;SECTION_SHELL;.984313726425171;.329411774873734;.419607847929
$001;1.;
$ANSA_COLOR;662110;SECTION_SOLID;.933333337306976;.650980412960052;.498039215803
$146;0.5;
$ANSA_COLOR;662120;SECTION_SOLID;.937254905700684;.333333343267441;.631372570991
$516;0.5;
$ANSA_COLOR;662210;SECTION_SOLID;.584313750267029;.427450984716415;.521568655967
$712;0.5;
$ANSA_COLOR;662220;SECTION_SOLID;.576470613479614;.749019622802734;.964705884456
$635;0.5;
$ANSA_COLOR;662310;SECTION_SOLID;.501960813999176;.839215695858002;.180392161011
$696;0.5;
$ANSA_COLOR;662320;SECTION_SOLID;.572549045085907;.121568627655506;.384313732385
$635;0.5;
$ANSA_COLOR;662410;SECTION_SHELL;.670588254928589;.800000011920929;.098039217293
$262;0.5;
$ANSA_COLOR;662420;SECTION_SOLID;.596078455448151;.200000002980232;.600000023841
$858;0.5;
$ANSA_COLOR;662510;SECTION_SHELL;.572549045085907;.333333343267441;.576470613479
$614;0.5;
$ANSA_COLOR;662520;SECTION_SOLID;.521568655967712;.443137258291245;.458823531866
$074;0.5;
$ANSA_COLOR;663110;SECTION_SHELL;.572549045085907;.070588238537312;.835294127464
$294;0.5;
$ANSA_COLOR;663120;SECTION_SOLID;.800000011920929;.070588238537312;.937254905700
$684;0.5;
$ANSA_COLOR;663210;SECTION_SHELL;0.74117648601532;0.34901961684227;.619607865810
$394;0.5;
$ANSA_COLOR;663220;SECTION_SOLID;.819607853889465;.729411780834198;.768627464771
$271;0.5;
$ANSA_COLOR;663310;SECTION_SHELL;.988235294818878;.482352942228317;.490196079015
$732;0.5;
$ANSA_COLOR;663320;SECTION_SOLID;.682352960109711;.415686279535294;.529411792755
$127;0.5;
$ANSA_COLOR;663410;SECTION_SHELL;.509803950786591;.090196080505848;.772549033164
$978;0.5;
$ANSA_COLOR;663420;SECTION_SOLID;.917647063732147;.776470601558685;.898039221763
$611;0.5;
$ANSA_COLOR;663510;SECTION_SHELL;.921568632125854;.298039227724075;.807843148708
$344;0.5;
$ANSA_COLOR;663520;SECTION_SOLID;.972549021244049;.607843160629272;.890196084976
$196;0.5;
$ANSA_COLOR;663610;SECTION_SHELL;.560784339904785;.768627464771271;.694117665290
$833;0.5;
$ANSA_COLOR;663620;SECTION_SOLID;.933333337306976;.388235300779343;.752941191196
$442;0.5;
$ANSA_COLOR;663710;SECTION_SHELL;.819607853889465;.623529434204102;.670588254928
$589;0.5;
$ANSA_COLOR;663720;SECTION_SOLID;0.5686274766922;.337254911661148;.1529411822557
$45;0.5;
$ANSA_COLOR;663810;SECTION_SHELL;.623529434204102;.905882358551025;.403921574354
$172;0.5;
$ANSA_COLOR;663820;SECTION_SOLID;.749019622802734;.705882370471954;0.30588236451
$149;0.5;
$ANSA_COLOR;664050;SECTION_SHELL;.764705896377563;.482352942228317;.384313732385
$635;0.5;
$ANSA_COLOR;664110;SECTION_SHELL;.709803938865662;.329411774873734;0.52549022436
$142;0.5;
$ANSA_COLOR;664120;SECTION_SOLID;.682352960109711;.152941182255745;0.78431373834
$61;0.5;
$ANSA_COLOR;664210;SECTION_SHELL;.788235306739807;.713725507259369;.250980406999
$588;0.5;
$ANSA_COLOR;664220;SECTION_SOLID;.968627452850342;.294117659330368;.600000023841
$858;0.5;
$ANSA_COLOR;664310;SECTION_SHELL;.960784316062927;.250980406999588;0.20392157137
$394;0.5;
$ANSA_COLOR;664320;SECTION_SOLID;.964705884456635;.141176477074623;.529411792755
$127;0.5;
$ANSA_COLOR;664410;SECTION_SHELL;.670588254928589;.058823529630899;.839215695858
$002;0.5;
$ANSA_COLOR;664420;SECTION_SOLID;.819607853889465;.572549045085907;.121568627655
$506;0.5;
$ANSA_COLOR;664510;SECTION_SHELL;.921568632125854;.035294119268656;.066666670143
$604;0.5;
$ANSA_COLOR;664520;SECTION_SOLID;.749019622802734;.235294118523598;.368627458810
$806;0.5;
$ANSA_COLOR;664550;SECTION_SHELL;.658823549747467;.078431375324726;0.56862747669
$22;0.5;
$ANSA_COLOR;665050;SECTION_SHELL;.839215695858002;.917647063732147;.658823549747
$467;0.5;
$ANSA_COLOR;665110;SECTION_SHELL;.960784316062927;.725490212440491;.141176477074
$623;0.5;
$ANSA_COLOR;665120;SECTION_SOLID;.768627464771271;.211764708161354;.066666670143
$604;0.5;
$ANSA_COLOR;665210;SECTION_SHELL;.705882370471954;.443137258291245;.200000002980
$232;0.5;
$ANSA_COLOR;665220;SECTION_SOLID;.721568644046783;.686274528503418;.215686276555
$061;0.5;
$ANSA_COLOR;665310;SECTION_SHELL;.713725507259369;.647058844566345;.815686285495
$758;0.5;
$ANSA_COLOR;665320;SECTION_SOLID;.549019634723663;.200000002980232;.811764717102
$051;0.5;
$ANSA_COLOR;665410;SECTION_SHELL;.592156887054443;.788235306739807;.788235306739
$807;0.5;
$ANSA_COLOR;665420;SECTION_SOLID;.572549045085907;.964705884456635;.737254917621
$613;0.5;
$ANSA_COLOR;665510;SECTION_SHELL;.505882382392883;.094117648899555;.345098048448
$563;0.5;
$ANSA_COLOR;665520;SECTION_SOLID;.666666686534882;.960784316062927;.317647069692
$612;0.5;
$ANSA_COLOR;665610;SECTION_SHELL;.905882358551025;.423529416322708;.207843139767
$647;0.5;
$ANSA_COLOR;665620;SECTION_SOLID;.764705896377563;.690196096897125;.580392181873
$322;0.5;
$ANSA_COLOR;665710;SECTION_SHELL;.537254929542542;.847058832645416;.121568627655
$506;0.5;
$ANSA_COLOR;665720;SECTION_SOLID;.831372559070587;.980392158031464;.360784322023
$392;0.5;
$ANSA_COLOR;665810;SECTION_SHELL;0.65490198135376;.603921592235565;.627451002597
$809;0.5;
$ANSA_COLOR;665820;SECTION_SOLID;.772549033164978;.050980392843485;.847058832645
$416;0.5;
$ANSA_COLOR;665910;SECTION_SHELL;.756862759590149;.858823537826538;.376470595598
$221;0.5;
$ANSA_COLOR;665920;SECTION_SOLID;.513725519180298;.925490200519562;.549019634723
$663;0.5;
$ANSA_COLOR;666010;SECTION_SHELL;.560784339904785;.607843160629272;.047058824449
$778;0.5;
$ANSA_COLOR;666020;SECTION_SOLID;.498039215803146;.364705890417099;.243137255311
$012;0.5;
$ANSA_COLOR;666050;SECTION_SHELL;.811764717102051;.003921568859369;.662745118141
$174;0.5;
$ANSA_COLOR;666210;SECTION_SHELL;.760784327983856;.694117665290833;.156862750649
$452;0.5;
$ANSA_COLOR;666220;SECTION_SOLID;.831372559070587;.717647075653076;.615686297416
$687;0.5;
$ANSA_COLOR;666310;SECTION_SHELL;.988235294818878;.011764706112444;.552941203117
$371;0.5;
$ANSA_COLOR;666320;SECTION_SOLID;.882352948188782;.345098048448563;.992156863212
$585;0.5;
$ANSA_COLOR;666410;SECTION_SHELL;.811764717102051;.372549027204514;.078431375324
$726;0.5;
$ANSA_COLOR;666420;SECTION_SOLID;.721568644046783;.215686276555061;.274509817361
$832;0.5;
$ANSA_COLOR;666510;SECTION_SHELL;.505882382392883;0.5686274766922;.8588235378265
$38;0.5;
$ANSA_COLOR;666520;SECTION_SOLID;.847058832645416;.329411774873734;.474509805440
$903;0.5;
$ANSA_COLOR;667700;SECTION_BEAM_ELFORM_6;0.52549022436142;.227450981736183;.6901
$96096897125;1.;
$ANSA_COLOR;667710;SECTION_BEAM_ELFORM_6;.752941191196442;.545098066329956;.0862
$74512112141;1.;
$ANSA_COLOR;667720;SECTION_BEAM_ELFORM_6;.772549033164978;0.10196078568697;0.392
$15686917305;1.;
$ANSA_COLOR;667730;SECTION_BEAM_ELFORM_6;.576470613479614;.905882358551025;0.611
$76472902298;1.;
$ANSA_COLOR;667740;SECTION_BEAM_ELFORM_6;.670588254928589;0.95686274766922;0.741
$17648601532;1.;
$ANSA_COLOR;667750;SECTION_BEAM_ELFORM_6;.552941203117371;0.24705882370472;0.784
$3137383461;1.;
$ANSA_COLOR;667760;SECTION_BEAM_ELFORM_6;.725490212440491;0.7843137383461;.73725
$4917621613;1.;
$ANSA_COLOR;667770;SECTION_BEAM_ELFORM_6;.690196096897125;0.5686274766922;.60000
$0023841858;1.;
$ANSA_COLOR;667780;SECTION_BEAM_ELFORM_6;.937254905700684;.592156887054443;.3725
$49027204514;1.;
$ANSA_COLOR;667790;SECTION_BEAM_ELFORM_6;.976470589637756;.862745106220245;.0588
$23529630899;1.;
$ANSA_COLOR;667800;SECTION_BEAM_ELFORM_6;.803921580314636;.380392163991928;0.654
$90198135376;1.;
$ANSA_COLOR;667810;SECTION_BEAM_ELFORM_6;.921568632125854;.137254908680916;.1607
$84319043159;1.;
$ANSA_COLOR;667820;SECTION_BEAM_ELFORM_6;0.82745099067688;.141176477074623;.5803
$92181873322;1.;
$ANSA_COLOR;667830;SECTION_BEAM_ELFORM_6;.521568655967712;0.39215686917305;.9098
$03926944733;1.;
$ANSA_COLOR;667840;SECTION_BEAM_ELFORM_6;.505882382392883;.882352948188782;.1529
$41182255745;1.;
$ANSA_COLOR;667870;SECTION_BEAM_ELFORM_6;.776470601558685;.623529434204102;0.305
$88236451149;1.;
$ANSA_COLOR;667880;SECTION_BEAM_ELFORM_6;.839215695858002;.603921592235565;.3686
$27458810806;1.;
$ANSA_COLOR;667890;SECTION_BEAM_ELFORM_6;.690196096897125;.831372559070587;.3411
$76480054855;1.;
$ANSA_COLOR;710050;SECTION_SHELL;0.82745099067688;.172549024224281;.490196079015
$732;0.5;
$ANSA_COLOR;760050;SECTION_SHELL;.623529434204102;.168627455830574;0.14509804546
$833;0.5;
$ANSA_USER_ATTRIBUTES;SECTION_SHELL;User/cad_material;TEXT;RW;YES;;;
$ANSA_USER_ATTRIBUTES;SECTION_SHELL;User/cad_thickness;TEXT;RW;YES;;;
$ANSA_USER_ATTRIBUTES;SECTION_SOLID;User/cad_material;TEXT;RW;YES;;;
$ANSA_PART;GROUP;ID;1178;NAME;main_left_shoulder.k;BELONGS_HERE;FORCED;PID_OFFSE
$T;0;COLOR;142;97;36;0;IS_COLOR_ACTIVE;1;PART_TYPE;Undefined;ATTRIBUTES;2;DM/Fil
$e Type;ANSA;DM/Status;WIP;CONTAINS;ANSAPART;1181,1186;
$ANSA_PART;PART;ID;1173;NAME;Hand;BELONGS_HERE;FORCED;STUDY_VERSION;0;PID_OFFSET
$;0;COLOR;152;181;208;0;IS_COLOR_ACTIVE;0;GET_COLOR_FROM_ID;1172;PART_TYPE;Undef
$ined;ATTRIBUTES;2;DM/File Type;ANSA;DM/Status;WIP;
$ANSA_PART;PART;ID;1181;MID;12403276;NAME;left_scapula_spon@12403276;BELONGS_HER
$E;FORCED;STUDY_VERSION;0;PID_OFFSET;0;COLOR;149;250;229;0;IS_COLOR_ACTIVE;1;PAR
$T_TYPE;Undefined;ATTRIBUTES;2;DM/File Type;ANSA;DM/Status;WIP;
$ANSA_PART;PART;ID;1186;MID;12402876;NAME;left_clavicle_spon@12402876;BELONGS_HE
$RE;FORCED;STUDY_VERSION;0;PID_OFFSET;0;COLOR;160;80;125;0;IS_COLOR_ACTIVE;1;PAR
$T_TYPE;Undefined;ATTRIBUTES;2;DM/File Type;ANSA;DM/Status;WIP;
$ANSA_PART;PART;ID;1195;NAME;Upper Arm Soft Tissue;BELONGS_HERE;FORCED;STUDY_VER
$SION;0;PID_OFFSET;0;COLOR;138;10;119;0;IS_COLOR_ACTIVE;1;PART_TYPE;Undefined;AT
$TRIBUTES;2;DM/File Type;ANSA;DM/Status;WIP;
$ANSA_PART;PART;ID;1198;NAME;Radius and Ulna;BELONGS_HERE;FORCED;STUDY_VERSION;0
$;PID_OFFSET;0;COLOR;200;4;68;0;IS_COLOR_ACTIVE;0;GET_COLOR_FROM_ID;1172;PART_TY
$PE;Undefined;ATTRIBUTES;2;DM/File Type;ANSA;DM/Status;WIP;
$ANSA_PART;PART;ID;1199;NAME;Humerus;BELONGS_HERE;FORCED;STUDY_VERSION;0;PID_OFF
$SET;0;COLOR;173;76;40;0;IS_COLOR_ACTIVE;0;GET_COLOR_FROM_ID;1172;PART_TYPE;Unde
$fined;ATTRIBUTES;2;DM/File Type;ANSA;DM/Status;WIP;
$ANSA_PART;PART;ID;1200;NAME;Scapula;BELONGS_HERE;FORCED;STUDY_VERSION;0;PID_OFF
$SET;0;COLOR;143;58;91;0;IS_COLOR_ACTIVE;1;PART_TYPE;Undefined;ATTRIBUTES;2;DM/F
$ile Type;ANSA;DM/Status;WIP;
$ANSA_PART;PART;ID;1201;NAME;Clavicle;BELONGS_HERE;FORCED;STUDY_VERSION;0;PID_OF
$FSET;0;COLOR;237;203;222;0;IS_COLOR_ACTIVE;1;PART_TYPE;Undefined;ATTRIBUTES;2;D
$M/File Type;ANSA;DM/Status;WIP;
*END
