# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: SAFER Validation Catalog
author: SAFER global arena
# logo: 

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

only_build_toc_files: true # Only build the files mentioned in the ToC

# Define the name of the latex output file for PDF builds
# latex:
#   latex_documents:
#     targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

html:
  announcement: " ⚠️ Work in Progress ⚠️"
  html_theme : "sphinx_book_theme"
  home_page_in_navbar: True
  # extensions : "jupyterhub_sphinx_theme"

html_theme_options :
  show_version_warning_banner: True
  
sphinx:
  recursive_update: True
