$
$ANSA_VERSION;22.1.0;
$
$
$ file created by  A N S A  Tue May 30 17:19:04 2023
$
$ output from :
$
$ C:/Users/yash/OneDrive - Chalmers/SAFE-UP_lumbarspine/IRC_validations/Oritz/no
$ minal/Untitled
$
$ Settings :
$
$ Output format : R13
$
$ Output : All
$
$
$
$
*KEYWORD
*CONSTRAINED_SHELL_IN_SOLID_PENALTY_ID
         1Anterior potting constrain                                            
        10         1         0         0
                                                            
*CONSTRAINED_SHELL_IN_SOLID_PENALTY_ID
         2Posterior potting constrain                                           
        10         2         0         0
                                                            
*END
